#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'rdfportal'

RDFPortal.logger = RDFPortal::Logger.new($stderr, level: ENV.fetch('RDFPORTAL_LOGGER_LEVEL', 'info'))

RDFPortal::CLI::Main.start(ARGV)
